### ISSUE TITLE
Build Error: Undefined comet.BlockInfo in `feature/wasm-patch-1` Branch

### ISSUE THREAD

**Issue by ComputerKeeda** [airchains-network/junction#20]
# Description:

I encountered a build error while trying to compile the `junctiond` binary on the `feature/wasm-patch-1` branch. The issue seems to arise from an undefined type `comet.BlockInfo` in the Cosmos SDK v0.50.9 codebase. Previously, the branch was using Cosmos SDK v0.50.3 and CometBFT v0.38.10, and the build was successful. The issue appeared after updating the Cosmos SDK to v0.50.9 and CometBFT to v0.38.11.

---

## Steps to Reproduce:

1. Checkout the branch:
   ```bash
   git checkout feature/wasm-patch-1
   ```

2. Run the build command:
   ```bash
   go build -tags "netgo" -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=junction -X github.com/cosmos/cosmos-sdk/version.AppName=junctiond -X github.com/cosmos/cosmos-sdk/version.Version=v0.2.0 -X github.com/cosmos/cosmos-sdk/version.Commit=32a330fea315a1a8110697a924f7dc76cba31c36 -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo" -X github.com/tendermint/tendermint/version.TMCoreSemVer=v0.38.11' -o ./build/junctiond ./cmd/junctiond
   ```

3. Error occurs:
   ```text
   # github.com/cosmos/cosmos-sdk/types
   ../../../../go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.9/types/context.go:66:29: undefined: comet.BlockInfo
   ../../../../go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.9/types/context.go:94:36: undefined: comet.BlockInfo
   ../../../../go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.50.9/types/context.go:309:48: undefined: comet.BlockInfo
   make: *** [Makefile:46: build] Error 1
   ```

---

## Additional Details:

- **Branch:** `feature/wasm-patch-1`
- **Cosmos SDK Version:** Updated from `v0.50.3` to `v0.50.9`
- **CometBFT Version:** Updated from `v0.38.10` to `v0.38.11`
- **Go Version:** `go1.23.2 linux/amd64`
- **OS:** Ubuntu 22.04

---

## Observations:

The error seems to be related to the `comet.BlockInfo` type, which is undefined in the Cosmos SDK codebase. It might be due to an incompatibility introduced between the updated Cosmos SDK v0.50.9 and CometBFT v0.38.11.

---

## Expected Behavior:

The `junctiond` binary should build successfully without errors.

---

## Suggested Steps to Resolve:

1. Confirm if the `comet.BlockInfo` type has been renamed or removed in the latest versions of CometBFT.
2. Verify the compatibility of Cosmos SDK v0.50.9 with CometBFT v0.38.11.
3. Check if Cosmos SDK v0.50.9 introduces changes that require updating the implementation in the affected files.
4. Update the `feature/wasm-patch-1` branch with a fix or provide a workaround for the version incompatibility.

**Comment by deadlium** [comment]
The build issue stems from an incompatibility between Cosmos SDK v0.50.9 and CometBFT v0.38.11, where `comet.BlockInfo` is undefined in the updated SDK.

**Comment by deadlium** [comment]
@ComputerKeeda Why not  we use Cosmos SDK v0.50.6 and CometBFT v0.38.6: This version pairing has been observed to be stable and compatible in similar contexts, potentially resolving the issue without significant changes.

**Comment by ComputerKeeda** [comment]
@deadlium Just changing this 2 won't do

I’ve made these changes, and I believe the initial error has been resolved. However, the build might still fail due to some remaining code adjustments.

**Changes Made:**
1. **Updated Go version** to `1.23.4` for compatibility and feature improvements.
2. **Replaced `gin-gonic/gin`** with `v1.8.1` to fix vulnerability (`GHSA-h395-qcrw-5vmq`).
3. **Replaced `goleveldb`** with `v1.0.1-0.20220721030215-126854af5e6d` to resolve query issues.
4. **Updated dependencies:**
   - Downgraded `cosmossdk.io/core` to `v0.11.1`.
   - Upgraded `prometheus/client_golang` to `v1.20.0`.
   - Upgraded `cosmossdk.io/log` to `v1.4.1`.

**Comment by deadlium** [comment]
Understood, I'll review the errors and verify the compatibility issues. Once the fixes are in place, I'll push the updated code with a stable build.

**Comment by ComputerKeeda** [comment]
G00d luck 👍🏼

**Comment by ComputerKeeda** [comment]
This issue has been resolved with commit [`9068cdc`](https://github.com/airchains-network/junction/commit/9068cdc6563dc9f3315e58ac674827ae1b4357ec). Closing it now. Feel free to reopen if further issues arise!
